#kubectl apply -f app-productos-deplyment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-productos
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-productos
  template:
    metadata:
      labels:
        app: app-productos
    spec:
      containers:
        - name: app-productos
          image: sterk55/app-productos
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-productos-service
spec:
  type: ClusterIP
  selector:
    app: app-productos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

